### ISSUE TITLE
Neovim TODO

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/.dotfiles#1]
## Basics
- [x] Neovim Tree
- [x] Neovim Tree-sitter
- [x] CMP 

## When I open a project
- [ ]  Open nvim-tree
- [ ]  Open a terminal session

## Language Server Protocol + Formatter
- [x] Lua 
- [ ]  Rust
- [ ]  Go 
- [ ]  Python 
- [ ]  C
- [ ]  Typescript
